# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/ChessGame.Api.csproj'
    arguments: '--configuration Release'
- task: CopyFiles@2
  inputs:
    Contents: '**/ChessGame.Api/bin/Release/netcoreapp3.1/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'